ecs:
  region: "sa-east-1" # must be string
  account: "134512440618" # must be string
  vpc:
    use_existing: true  # need to update the code when it's No
    vpc_id: vpc-66c9a003
    vpc_name: vpc
  ecs_cluster:
    domain_name: cluster
    relase_label: 'emr-6.10.0'
    service_role_name: emr-service
    container_name: 'ocr_api'
  ec2:
    vpn_peer: '172.31.27.177'
    domain_name: 'easyprocess-ehs.com.br'